objective:
  - MCP Regression[reg=0.1,gamma=3]
  - MCP Regression[reg=0.01,gamma=3]
  - MCP Regression[reg=0.001,gamma=3]
dataset:
  - simulated[n_samples=500,n_features=2000,scale=[True,False]]
  - libsvm[dataset=colon-cancer]
  # - libsvm[dataset=rcv1.binary]
n-repetitions: 5
n-jobs: 12
timeout: 3000
solver:
  - cd
  - skglm
  - GIST
  - PGD
  - WorkSet_CD

output: mcp-neurips